
replicaCount: _REPLICAS_

image:
  repository: _REGISTRY_/_PROJECT_ID_/_APP_NAME_
  tag: _VERSION_
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 80
  containerPort: _PORT_

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.com/health-checks: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    cpu: 700m
    memory: 500Mi
  requests:
    cpu: 500m
    memory: 300Mi

livenessProbe:
  httpGet:
    path: /
    port: http
    scheme: HTTP
  initialDelaySeconds: 150
  periodSeconds: 50
  timeoutSeconds: 5
readinessProbe:
  httpGet:
    path: /
    port: http
    scheme: HTTP
  initialDelaySeconds: 150
  periodSeconds: 50
  timeoutSeconds: 3

nodeSelector: {}

tolerations: []

affinity: {}

configmap:
  APP_VERSION: _VERSION_
  API_BASE_URL: http://crawler-manager._DEPLOYMENT_TYPE_.channelprecision.com/v1/
  VUE_APP_API_BASE_URL: http://mw-api._DEPLOYMENT_TYPE_.channelprecision.com/
  VUE_APP_MW_API_BASE_URL: http://mw-api._DEPLOYMENT_TYPE_.channelprecision.com
  VUE_APP_MW_DEV_ACCESS_TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJ1c2VyX2lkIjoiNjZjZTlhMTktZDJkNS00MmY3LThkMTktZDQ2ZmNjMzg1ZTJjIiwidXNlcm5hbWUiOiJ1c2VyX29lQG1haWxpbmF0b3IuY29tIiwiZXhwIjoxNTY0NTQ0NTYyLCJjbGllbnRfaWQiOiI5N2NlNTVmMy0xOGIyLTRkZWMtODBiNi01MDk3OWE1ZDcwOGIiLCJ1c2VyX2NsaWVudF9pZCI6Ijg5ZmViMzU3LTJlYTctNGQ5MS05MTNiLTNhMTk1ODdhNmZkYyIsImxhc3RfbW9kaWZpZWRfc2V0dGluZ3MiOiIyMDE5LTA2LTI3IDA4OjAwOjQyLjc0NDIzMSswMDowMCIsImVtYWlsIjoidXNlcl9vZUBtYWlsaW5hdG9yLmNvbSIsIm9yaWdfaWF0IjoxNTYxOTUyNTYyfQ.qLw7DQfspezmUvrCJ-C7IPt7csdh9cRUKoaIWPJF6HMHY9mIbQvQuY4-HtKs10Z23g7MDs9g92AIuwkKj7h271NZCo-J_jOWdpoTbUI2IrYSxzOEocaHuk6hoUhYusKhHF6Vtn7OP74qfvo3kFXPRU19il0Wod6ivpwbibWwhpN2HaX-6ZIcZ-MlU-Yyn0XX2XWiwUEaAnrqKCNmLNSB3ceOT3952ZJJTKfBeaIq7_kisp_CiXuwUVLFWEzw55bUmR8hriRwtFotX4B8O8mh0V2Oo01eGYinK71RpcjaNXwOoh3HCBv7ACqs08taNqokgpavfpQzsd-oGHiTAlpC-A
  VUE_APP_MW_DEV_CLIENT_ID: 97ce55f3-18b2-4dec-80b6-50979a5d708b
