// default params
export const GET_DEFAULT_PARAMS = 'GET_DEFAULT_PARAMS'
export const GET_REPORT_MARKETPLACE_HISTORY_DEFAULT_PARAMS = 'GET_REPORT_MARKETPLACE_HISTORY_DEFAULT_PARAMS'
export const GET_DEFAULT_AMAZON_MAP_PARAMS = 'GET_DEFAULT_AMAZON_MAP_PARAMS'
export const GET_DEFAULT_SELLER_ENFORCEMENT_PARAMS = 'GET_DEFAULT_SELLER_ENFORCEMENT_PARAMS'

// reports
export const FETCH_LIST_REPORTS = 'FETCH_LIST_REPORTS'
export const SET_LIST_REPORTS = 'SET_LIST_REPORTS'
export const SET_LIST_SELLER_ENFORCEMENTS = 'SET_LIST_SELLER_ENFORCEMENTS'
export const SET_LIST_REPORT_MARKETPLACE_HISTORY = 'SET_LIST_REPORT_MARKETPLACE_HISTORY'
export const GET_LIST_REPORTS = 'GET_LIST_REPORTS'
export const GET_LIST_SELLER_ENFORCEMENT = 'GET_LIST_SELLER_ENFORCEMENT'
export const REMOVE_REPORTS = 'REMOVE_REPORTS'
export const REMOVE_SELLER_ENFORCEMENT = 'REMOVE_SELLER_ENFORCEMENT'
export const CHANGE_FREQUENCY_SELLER_ENFORCEMENT = 'CHANGE_FREQUENCY_SELLER_ENFORCEMENT'
export const GET_REPORT_LOADING = 'GET_REPORT_LOADING'
export const SET_REPORT_LOADING = 'SET_REPORT_LOADING'
export const GET_GS_REPORT_LOADING = 'GET_GS_REPORT_LOADING'
export const SET_GS_REPORT_LOADING = 'SET_GS_REPORT_LOADING'
export const RESET_REPORTS = 'RESET_REPORTS'
export const SET_IS_DOWLOADING_REPORT = 'SET_IS_DOWLOADING_REPORT'
export const UPDATE_TOTAL_GS_MAP = 'UPDATE_TOTAL_GS_MAP'

// loading
export const GET_SELLER_ENFORCEMENT_LOADING = 'GET_SELLER_ENFORCEMENT_LOADING'
export const SET_SELLER_ENFORCEMENT_LOADING = 'SET_SELLER_ENFORCEMENT_LOADING'

export const GET_MAP_PRICING_LOADING = 'GET_MAP_PRICING_LOADING'
export const SET_MAP_PRICING_LOADING = 'SET_MAP_PRICING_LOADING'

export const GET_MAP_PRICING_GS_LOADING = 'GET_MAP_PRICING_GS_LOADING'
export const SET_MAP_PRICING_GS_LOADING = 'SET_MAP_PRICING_GS_LOADING'

export const GET_SELLER_LOADING = 'GET_SELLER_LOADING'
export const SET_SELLER_LOADING = 'SET_SELLER_LOADING'

export const GET_LISTING_LOADING = 'GET_LISTING_LOADING'
export const SET_LISTING_LOADING = 'SET_LISTING_LOADING'

export const GET_HISTORY_LOADING = 'GET_HISTORY_LOADING'
export const SET_HISTORY_LOADING = 'SET_HISTORY_LOADING'

export const GET_INVENTORY_HISTORY_LOADING = 'GET_INVENTORY_HISTORY_LOADING'
export const SET_INVENTORY_HISTORY_LOADING = 'SET_INVENTORY_HISTORY_LOADING'

export const FETCH_ONE_REPORT = 'FETCH_ONE_REPORT'
export const EDIT_ONE_REPORT = 'EDIT_ONE_REPORT'
export const SET_ONE_REPORT = 'SET_ONE_REPORT'
export const GET_ONE_REPORT = 'FETCH_ONE_REPORT'
export const GET_ONE_SELLER_ENFORCEMENT = 'GET_ONE_SELLER_ENFORCEMENT'
export const SET_ONE_GS_REPORT = 'SET_ONE_GS_REPORT'
export const GET_ONE_GS_REPORT = 'FETCH_ONE_GS_REPORT'

export const RUN_A_REPORT = 'RUN_A_REPORT'
export const CANCEL_A_REPORT = 'CANCEL_A_REPORT'
export const REAL_TIME_STATUS_RUN = 'REAL_TIME_STATUS_RUN'
export const CHANGE_REPORT_SCHEDULE_MODE = 'CHANGE_REPORT_SCHEDULE_MODE'

export const REMOTE_EDIT_REPORT = 'REMOTE_EDIT_REPORT'
export const REMOTE_EDIT_SELLER_ENFORCEMENT = 'REMOTE_EDIT_SELLER_ENFORCEMENT'
export const REMOTE_MANUAL_SEND_MAIL_SELLER_ENFORCEMENT = 'REMOTE_MANUAL_SEND_MAIL_SELLER_ENFORCEMENT'
export const REMOTE_POST_REPORT = 'REMOTE_POST_REPORT'
export const REMOTE_POST_SELLER_ENFORCEMENT = 'REMOTE_POST_SELLER_ENFORCEMENT'
export const REMOTE_SEARCH_REPORTS = 'REMOTE_SEARCH_REPORTS'
export const REMOTE_SORT_REPORTS = 'REMOTE_SORT_REPORTS'

export const GET_VALID_AMAZON_REPORTS = 'GET_VALID_AMAZON_REPORTS'
export const GET_VALID_GS_REPORTS = 'GET_VALID_GS_REPORTS'

export const RUN_AN_INVENTORY = 'RUN_AN_INVENTORY'
export const CANCEL_AN_INVENTORY = 'CANCEL_AN_INVENTORY'
export const SET_INVENTORY_STATUS_LIST_REPORTS = 'SET_INVENTORY_STATUS_LIST_REPORTS'
export const FETCH_INVENTORY_HISTORY = 'FETCH_INVENTORY_HISTORY'
export const GET_INVENTORY_HISTORY = 'GET_INVENTORY_HISTORY'
export const SET_INVENTORY_HISTORY = 'SET_INVENTORY_HISTORY'
export const FETCH_INVENTORY_SCHEDULES = 'FETCH_INVENTORY_SCHEDULES'
export const GET_INVENTORY_SCHEDULES = 'GET_INVENTORY_SCHEDULES'
export const SET_INVENTORY_SCHEDULES = 'SET_INVENTORY_SCHEDULES'
export const ADD_INVENTORY_SCHEDULES = 'ADD_INVENTORY_SCHEDULES'
export const REMOVE_INVENTORY_SCHEDULES = 'REMOVE_INVENTORY_SCHEDULES'
export const REMOVE_INVENTORY_SCHEDULE = 'REMOVE_INVENTORY_SCHEDULE'

// marketplaces
export const FETCH_MARKETPLACES = 'FETCH_MARKETPLACES'
export const SET_MARKETPLACES = 'SET_MARKETPLACES'
export const GET_MARKETPLACES = 'GET_MARKETPLACES'

// map price
export const FETCH_LIST_MAPS = 'FETCH_LIST_MAPS'
export const FETCH_LIST_SELLER_ENFORCEMENTS = 'FETCH_LIST_SELLER_ENFORCEMENTS'
export const FETCH_LIST_SELLER_ENFORCEMENT_HISTORY = 'FETCH_LIST_SELLER_ENFORCEMENT_HISTORY'
export const FETCH_LIST_GS_MAPS = 'FETCH_LIST_GS_MAPS'
export const FETCH_LIST_REPORT_MARKETPLACE_HISTORY = 'FETCH_LIST_REPORT_MARKETPLACE_HISTORY'
export const REMOTE_IMPORT_CSV_MAPS = 'REMOTE_IMPORT_CSV_MAPS'
export const GET_MAPS = 'GET_MAPS'
export const GET_SELLER_ENFORCEMENT_HISTORY_DATES = 'GET_SELLER_ENFORCEMENT_HISTORY_DATES'
export const GET_GS_MAPS = 'GET_GS_MAPS'
export const GET_REPORT_MARKETPLACE_HISTORY = 'GET_REPORT_MARKETPLACE_HISTORY'
export const SET_LIST_MAPS = 'SET_LIST_MAPS'
export const SET_LIST_MAPS_TOTAL = 'SET_LIST_MAPS_TOTAL'
export const SET_LIST_GS_MAPS = 'SET_LIST_GS_MAPS'
export const SET_PROCESS_MAPS = 'SET_PROCESS_MAPS'
export const GET_PROCESS_MAPS = 'GET_PROCESS_MAPS'
export const REMOVE_MAP = 'REMOVE_MAP'
export const REMOVE_GS_MAP = 'REMOVE_GS_MAP'
export const GET_ONE_MAP = 'GET_ONE_MAP'
export const SET_ONE_MAP = 'SET_ONE_MAP'
export const GET_ONE_GS_MAP = 'GET_ONE_GS_MAP'
export const SET_ONE_GS_MAP = 'SET_ONE_GS_MAP'
export const FETCH_ONE_MAP = 'FETCH_ONE_MAP'
export const FETCH_ONE_GS_MAP = 'FETCH_ONE_GS_MAP'
export const UPDATE_MAP = 'UPDATE_MAP'
export const UPDATE_GS_MAP = 'UPDATE_GS_MAP'
export const ACCEPT_DISCOVERED_GPID = 'ACCEPT_DISCOVERED_GPID'
export const REMOVE_DISCOVERED_GPID = 'REMOVE_DISCOVERED_GPID'
export const DENIED_DISCOVERED_GPID = 'DENIED_DISCOVERED_GPID'
export const EDIT_GPID_DISCOVERY_NEEDED = 'EDIT_GPID_DISCOVERY_NEEDED'

export const FETCH_URL_EXPORT = 'FETCH_URL_EXPORT'
export const FETCH_SI_SELLER_URL_EXPORT = 'FETCH_SI_SELLER_URL_EXPORT'
export const SET_URL_EXPORT = 'SET_URL_EXPORT'
export const SET_SI_SELLER_URL_EXPORT = 'SET_SI_SELLER_URL_EXPORT'

export const FETCH_URL_GS_MAP_EXPORT = 'FETCH_URL_GS_MAP_EXPORT'
export const SET_URL_GS_MAP_EXPORT = 'SET_URL_GS_MAP_EXPORT'

export const REMOTE_EDIT_SETTING = 'REMOTE_EDIT_SETTING'
export const FETCH_SETTING = 'FETCH_SETTING'
export const SEND_POLICY_NOTIFICATION = 'SEND_POLICY_NOTIFICATION'

export const GET_BRAND_NAMES = 'GET_BRAND_NAMES'
export const GET_GS_BRAND_NAMES = 'GET_GS_BRAND_NAMES'

// images
export const REMOTE_UPLOAD_IMAGES = 'REMOTE_UPLOAD_IMAGES'
export const REMOTE_UPLOAD_FILES = 'REMOTE_UPLOAD_FILES'
export const SET_IMAGES = 'SET_IMAGES'

// job
export const REMOTE_GET_LINK_DOWNLOAD_JOB = 'REMOTE_GET_LINK_DOWNLOAD_JOB'

//
export const FETCH_SI_DASHBOARD_COMPLIED_ACTIVE_ROGUE = 'FETCH_SELLER_DASHBOARD_COMPLIED_ACTIVE_ROGUE'
export const FETCH_SI_DASHBOARD_COMPLETION = 'FETCH_SI_DASHBOARD_COMPLETION'
export const FETCH_SI_DASHBOARD_GMR = 'FETCH_SI_DASHBOARD_GMR'
export const FETCH_SI_DASHBOARD_ARBITRAGE = 'FETCH_SI_DASHBOARD_ARBITRAGE'
export const FETCH_SI_DASHBOARD_TOTAL_LISTING = 'FETCH_SI_DASHBOARD_TOTAL_LISTING'
export const FETCH_SI_DASHBOARD_SELLER_STATUS = 'FETCH_SI_DASHBOARD_SELLER_STATUS'
export const FETCH_DATA_VIOLATOR = 'FETCH_DATA_VIOLATOR'
export const FETCH_ALL_WIDGET = 'FETCH_ALL_WIDGET'
export const FETCH_DATA_VIOLATOR_WITH_INVENTORY = 'FETCH_DATA_VIOLATOR_WITH_INVENTORY'
export const FETCH_DATA_TOP_VIOLATED_PRODUCTS_7D =
  'FETCH_DATA_TOP_VIOLATED_PRODUCTS_7D'
export const FETCH_DATA_NEW_1ST_TIME = 'FETCH_DATA_NEW_1ST_TIME'
export const FETCH_DATA_NEW_2ND_TIME = 'FETCH_DATA_NEW_2ND_TIME'
export const FETCH_DATA_SELLER_VIOLATIONS_7D = 'FETCH_DATA_SELLER_VIOLATIONS_7D'
export const FETCH_DATA_AVG_PERCENTAGE_OFF_MAP =
  'FETCH_DATA_AVG_PERCENTAGE_OFF_MAP'
export const FETCH_DATA_NEW_REPEAT_VIOLATORS = 'FETCH_DATA_NEW_REPEAT_VIOLATORS'
export const FETCH_DATA_ALL_REPEAT_OFFENDERS = 'FETCH_DATA_ALL_REPEAT_OFFENDERS'
export const FETCH_DATA_NUMBER_OF_VIOLATIONS = 'FETCH_DATA_NUMBER_OF_VIOLATIONS'
export const FETCH_DATA_NUMBER_OF_VIOLATIONS_VIOLATORS =
  'FETCH_DATA_NUMBER_OF_VIOLATIONS_VIOLATORS'
export const FETCH_DOWNLOAD_DAILY_VIOLATIONS = 'FETCH_DOWNLOAD_DAILY_VIOLATIONS'
export const FETCH_DOWNLOAD_DAILY_VIOLATIONS_WITH_INVENTORY = 'FETCH_DOWNLOAD_DAILY_VIOLATIONS_WITH_INVENTORY'
export const FETCH_DOWNLOAD_NEW_REPEAT_VIOLATORS =
  'FETCH_DOWNLOAD_NEW_REPEAT_VIOLATORS'
export const FETCH_DATA_HISTORICAL = 'FETCH_DATA_HISTORICAL'
export const FETCH_DATE_HISTORICAL = 'FETCH_DATE_HISTORICAL'
export const SET_DATA_VIOLATOR = 'SET_DATA_VIOLATOR'
export const GET_DATA_VIOLATOR = 'GET_DATA_VIOLATOR'
export const SET_DATA_VIOLATOR_WITH_INVENTORY = 'SET_DATA_VIOLATOR_WITH_INVENTORY'
export const GET_DATA_VIOLATOR_WITH_INVENTORY = 'GET_DATA_VIOLATOR_WITH_INVENTORY'
export const GET_DATA_NEW_1ST_TIME = 'GET_DATA_NEW_1ST_TIME'
export const SET_DATA_NEW_1ST_TIME = 'SET_DATA_NEW_1ST_TIME'
export const GET_DATA_NEW_2ND_TIME = 'GET_DATA_NEW_2ND_TIME'
export const SET_DATA_NEW_2ND_TIME = 'SET_DATA_NEW_2ND_TIME'
export const GET_DATA_TOP_VIOLATED_PRODUCTS_7D =
  'GET_DATA_TOP_VIOLATED_PRODUCTS_7D'
export const SET_DATA_TOP_VIOLATED_PRODUCTS_7D =
  'SET_DATA_TOP_VIOLATED_PRODUCTS_7D'
export const GET_DATA_SELLER_VIOLATIONS_7D = 'GET_DATA_SELLER_VIOLATIONS_7D'
export const SET_DATA_SELLER_VIOLATIONS_7D = 'SET_DATA_SELLER_VIOLATIONS_7D'
export const GET_DATA_AVG_PERCENTAGE_OFF_MAP = 'GET_DATA_AVG_PERCENTAGE_OFF_MAP'
export const SET_DATA_AVG_PERCENTAGE_OFF_MAP = 'SET_DATA_AVG_PERCENTAGE_OFF_MAP'
export const GET_DATA_NEW_REPEAT_VIOLATORS = 'GET_DATA_NEW_REPEAT_VIOLATORS'
export const SET_DATA_NEW_REPEAT_VIOLATORS = 'SET_DATA_NEW_REPEAT_VIOLATORS'
export const GET_DATA_ALL_REPEAT_OFFENDERS = 'GET_DATA_ALL_REPEAT_OFFENDERS'
export const SET_DATA_ALL_REPEAT_OFFENDERS = 'SET_DATA_ALL_REPEAT_OFFENDERS'
export const GET_DATA_NUMBER_OF_VIOLATIONS = 'GET_DATA_NUMBER_OF_VIOLATIONS'
export const SET_DATA_NUMBER_OF_VIOLATIONS = 'SET_DATA_NUMBER_OF_VIOLATIONS'
export const GET_DATA_NUMBER_OF_VIOLATIONS_VIOLATORS =
  'GET_DATA_NUMBER_OF_VIOLATIONS_VIOLATORS'
export const SET_DATA_NUMBER_OF_VIOLATIONS_VIOLATORS =
  'SET_DATA_NUMBER_OF_VIOLATIONS_VIOLATORS'
export const GET_DATA_HISTORICAL = 'GET_DATA_HISTORICAL'
export const SET_DATA_HISTORICAL = 'SET_DATA_HISTORICAL'
export const GET_DATE_HISTORICAL = 'GET_DATE_HISTORICAL'
export const SET_DATE_HISTORICAL = 'SET_DATE_HISTORICAL'
export const GET_DATA_CONFIG_VIOLATOR = 'GET_DATA_CONFIG_VIOLATOR'
export const GET_DATA_CONFIG_HISTORICAL = 'GET_DATA_CONFIG_HISTORICAL'
export const TOGGLE_TABLE_LOADER = 'TOGGLE_TABLE_LOADER'
export const GET_TABLE_LOADER = 'GET_TABLE_LOADER'
export const SET_TABLE_LOADER = 'SET_TABLE_LOADER'
export const GET_DOWNLOAD_DAILY_LOADER = 'GET_DOWNLOAD_DAILY_LOADER'
export const SET_DOWNLOAD_DAILY_LOADER = 'SET_DOWNLOAD_DAILY_LOADER'
export const GET_DOWNLOAD_DAILY_WITH_INVENTORY_LOADER = 'GET_DOWNLOAD_DAILY_WITH_INVENTORY_LOADER'
export const SET_DOWNLOAD_DAILY_WITH_INVENTORY_LOADER = 'SET_DOWNLOAD_DAILY_WITH_INVENTORY_LOADER'
export const GET_DOWNLOAD_NEW_REPEAT_LOADER = 'GET_DOWNLOAD_NEW_REPEAT_LOADER'
export const SET_DOWNLOAD_NEW_REPEAT_LOADER = 'SET_DOWNLOAD_NEW_REPEAT_LOADER'
export const DOWNLOAD_DAILY_VIOLATIONS = 'DOWNLOAD_DAILY_VIOLATIONS'
export const DOWNLOAD_DAILY_VIOLATIONS_WITH_INVENTORY = 'DOWNLOAD_DAILY_VIOLATIONS_WITH_INVENTORY'
export const DOWNLOAD_NEW_REPEAT_VIOLATORS = 'DOWNLOAD_NEW_REPEAT_VIOLATORS'
export const DOWNLOAD_SI_DASHBOARD_WIDGET = 'DOWNLOAD_SI_DASHBOARD_WIDGET'

// data source map connection
export const GET_DS_MAPS = 'GET_DS_MAPS'

// PERMISSIONS
export const FETCH_PERMISSIONS = 'FETCH_PERMISSIONS'
export const SET_PERMISSIONS = 'SET_PERMISSIONS'
export const GET_PERMISSIONS = 'GET_PERMISSIONS'
// Plan
export const SET_PLAN_CONFIG = 'SET_PLAN_CONFIG'
export const GET_PLAN_CONFIG = 'GET_PLAN_CONFIG'
// Plan stats
export const SET_ORGANIZATION_STATS = 'SET_ORGANIZATION_STATS'
export const GET_ORGANIZATION_STATS = 'GET_ORGANIZATION_STATS'
// is oe user
export const SET_ORG_IS = 'SET_ORG_IS'
export const GET_ORG_IS = 'GET_ORG_IS'
// firebase realtime
export const LISTEN_TO_FIREBASE_EVENT_REPORT = 'LISTEN_TO_FIREBASE_EVENT_REPORT'
export const UPDATE_REPORT_PROGRESS = 'UPDATE_REPORT_PROGRESS'
export const RESET_REPORT_RUN_NR = 'RESET_REPORT_RUN_NR'

// date
export const GET_SELECTED_DATE = 'GET_SELECTED_DATE'
export const SET_SELECTED_DATE = 'SET_SELECTED_DATE'

// import reports
export const FETCH_IMPORT_REPORTS = 'FETCH_IMPORT_REPORTS'
export const SET_IMPORT_REPORTS = 'SET_IMPORT_REPORTS'
export const GET_LIST_IMPORT_REPORTS = 'GET_LIST_IMPORT_REPORTS'

export const GET_LIST_REPORT_LOADING = 'GET_LIST_REPORT_LOADING'
export const SET_LIST_REPORT_LOADING = 'SET_LIST_REPORT_LOADING'

export const SET_EDIT_FORM_LIST_REPORTS = 'SET_EDIT_FORM_LIST_REPORTS'
export const GET_AMAZON_LIST_REPORTS = 'GET_AMAZON_LIST_REPORTS'
export const GET_GS_LIST_REPORTS = 'GET_GS_LIST_REPORTS'

export const GET_LIST_DISCOVERED_GPID = 'GET_LIST_DISCOVERED_GPID'
export const UPDATE_LIST_DISCOVERED_GPID = 'UPDATE_LIST_DISCOVERED_GPID'
export const RESET_LIST_DISCOVERED_GPID = 'RESET_LIST_DISCOVERED_GPID'
